### PR TITLE
Specify inference server container name

### LINKED ISSUE #474: Kfserving cannot work when knative serving container-name-template is not default value
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Kfserving cannot work when knative serving container-name-template is not default value,

```
# kubectl get configmap config-defaults -oyaml -nknative-serving
apiVersion: v1
data:
 ...
  container-name-template: serving-container
```
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by hougangliu**
For now inferenceservice container name is not specified, knative serving will generates the corresponding Pod with a name from `container-name-template` value in ConfigMap config-defaults in knative-serving namespace, which is editable.

For now, inferenceservice webhook mounts volume on the container with hard-code name "user-container", once `container-name-template` changed, inferenceservice cannot work.

so we can add a name to all kinds of component container, not using knative default one.
Fixes #474

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/475)

### CODE REVIEW

File: pkg/apis/serving/v1alpha2/framework_custom.go [hunk 1]
```diff
@@ -49,5 +49,8 @@ func (c *CustomSpec) Validate(config *InferenceServicesConfig) error {
 	if err != nil {
 		return fmt.Errorf("Custom container validation error: %s", err.Error())
 	}
+	if c.GetStorageUri() != "" && c.Container.Name != constants.InferenceServiceContainerName {
```
Comment (ellis-bigelow) [inline pkg/apis/serving/v1alpha2/framework_custom.go]: Can you take a look at our other validators and implement it in the same style.

File: pkg/constants/constants.go [hunk 2]
```diff
@@ -114,6 +114,11 @@ const (
 	ArgumentPredictorHost = "--predictor_host"
 )
 
+// InferenceService container name
+const (
+	InferenceServiceContainerName = "kfserving-container"
```
Comment (ellis-bigelow) [inline pkg/constants/constants.go]: Hmm -- should we instead name this after the Component name? I.e. Predictor.

**Comment by ellis-bigelow** [comment]
Interesting issue. Thanks for calling this out. Do other users of Knative have this problem?

**Comment by hougangliu** [comment]
> Interesting issue. Thanks for calling this out. Do other users of Knative have this problem?

The reason why kfserving have such issue is that kfserving try to specify the `user-container` container and mount volume on it.
I think for most users of Knative don't need modify the Pod, so I think for most knative users, there is no such problem

File: pkg/apis/serving/v1alpha2/framework_custom.go (hunk 1 above)
Comment (hougangliu) [reply pkg/apis/serving/v1alpha2/framework_custom.go]: In other validators, they doesn't need directly define container (we generate container based on all kinds of field), so for custom, it's an exception so that we need validate the container directly.

File: pkg/constants/constants.go (hunk 2 above)
Comment (hougangliu) [reply pkg/constants/constants.go]: sure, we can do it, but it will make logic more complex but will not introducing any obvious benefit.
for example, we want to check a Predictor Pod information, its name already has `Predictor` (for example `flowers-sample-predictor-default-vh8vg-deployment-74d59c7bwmkwc`), we can know the Pod is for Predictor, then we get its yaml definition, I think it is enough to recognize "kfserving-container" container.

File: pkg/apis/serving/v1alpha2/framework_custom.go (hunk 1 above)
Comment (ellis-bigelow) [reply pkg/apis/serving/v1alpha2/framework_custom.go]: Two things. I think we should just default the container name to our constant name. However, if the user provides a name, we should respect it. As I understand it, this won't have any issue with knative configmaps since the container name is specified by the user.

This also avoids putting weird restrictions on the user's container name. 

What I meant about the error message is typically we expose the error string as a constant and then validate it in the other tests.

File: pkg/constants/constants.go (hunk 2 above)
Comment (ellis-bigelow) [reply pkg/constants/constants.go]: Noo what I mean is just use the string value of this: https://github.com/kubeflow/kfserving/blob/master/pkg/constants/constants.go#L94

Comment (hougangliu) [reply pkg/constants/constants.go]: for now explainer also need the container name to mount volume, I think we can just use a unified name

File: pkg/apis/serving/v1alpha2/framework_custom.go (hunk 1 above)
Comment (hougangliu) [reply pkg/apis/serving/v1alpha2/framework_custom.go]: If a user specifies arbitrarily container name, into which container we should mount model volume in mutating webhook (for now, we mount volume into the container with "user-container" name)?
In fact, for now, if user custom a container with a name and storage Url env, it cannot work (it is an issue)

File: pkg/constants/constants.go (hunk 2 above)
Comment (ellis-bigelow) [reply pkg/constants/constants.go]: I'm thinking ahead to when we might want to host multiple containers in the same pod for performance reasons. We might not even be using knative (and just raw deployments).

It should be pretty trivial to simply name the container based off of the component that it is (i.e. predictor/explainer/transformer).

Does that make sense?

Comment (hougangliu) [reply pkg/constants/constants.go]: This PR introduces specified container name to solve container recognition in webhook for knative constraints which cannot support mount volume. 
if in future we only use deployment, we can just define the volume mount in deployment definition directly. Then I think introducing container name is no meaning then.

File: pkg/apis/serving/v1alpha2/framework_custom.go (hunk 1 above)
Comment (ellis-bigelow) [reply pkg/apis/serving/v1alpha2/framework_custom.go]: I see. It would be a bit awkward to read the kfservice to grab the container name while mutating pods.

File: pkg/constants/constants.go (hunk 2 above)
Comment (ellis-bigelow) [reply pkg/constants/constants.go]: Sure.

**Comment by hougangliu** [comment]
rebased to pass `kubeflow-kfserving-presubmit`
